"""
reporting.py — turn the results dict into files a human (and LaTeX) can read.

  results/metrics.json            every number, machine-readable
  results/*.csv                   the main tables
  report/generated/macros.tex     \\newcommand per headline number
  report/generated/tab_*.tex      the tables the report \\input-s

The report never contains a hand-typed result: re-running
``python -m src.run_all`` regenerates all of it.
"""

from __future__ import annotations

import json
import re
import unicodedata
from pathlib import Path

import numpy as np
import pandas as pd

from . import config
from .data_prep import normalize_name


# --------------------------------------------------------------------------- utils
def to_jsonable(obj):
    if isinstance(obj, dict):
        return {str(k): to_jsonable(v) for k, v in obj.items() if not str(k).startswith("_")}
    if isinstance(obj, (list, tuple)):
        return [to_jsonable(v) for v in obj]
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.floating,)):
        return None if np.isnan(obj) else float(obj)
    if isinstance(obj, float) and np.isnan(obj):
        return None
    if isinstance(obj, Path):
        return str(obj)
    return obj


def tex_escape(text) -> str:
    """Escape LaTeX specials and drop characters the T1 Times font cannot print."""
    s = str(text)
    s = unicodedata.normalize("NFKD", s)
    s = "".join(ch for ch in s if ord(ch) < 128 or ch in "–—±²")
    repl = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
            "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\^{}",
            "<": r"$<$", ">": r"$>$", "–": "--", "—": "---", "±": r"$\pm$", "²": r"$^2$"}
    return "".join(repl.get(ch, ch) for ch in s)


def num(x, d: int = 3) -> str:
    """Number for LaTeX: thousands separated with {,}; NaN -> '--'."""
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return "--"
    if isinstance(x, (int, np.integer)) or (isinstance(x, float) and d == 0):
        return f"{int(round(x)):,}".replace(",", "{,}")
    return f"{x:,.{d}f}".replace(",", "{,}")


def pct(x, d: int = 1) -> str:
    return "--" if x is None else f"{100 * x:.{d}f}\\%"


def pm(ms, d: int = 3) -> str:
    return "--" if ms is None else f"{num(ms[0], d)}\\ensuremath{{\\pm}}{num(ms[1], d)}"


def sci(x) -> str:
    """1e-05 -> 10^{-5}; 3e-05 -> 3\\times10^{-5}."""
    m, e = f"{x:.0e}".split("e")
    e = int(e)
    return f"\\ensuremath{{10^{{{e}}}}}" if m == "1" else f"\\ensuremath{{{m}\\times10^{{{e}}}}}"


def _macro_name(name: str) -> str:
    if not re.fullmatch(r"[A-Za-z]+", name):
        raise ValueError(f"LaTeX macro names must be letters only: {name}")
    return name


class TexWriter:
    def __init__(self, out_dir: Path):
        self.out_dir = Path(out_dir)
        self.out_dir.mkdir(parents=True, exist_ok=True)
        self.macros: dict[str, str] = {}

    def macro(self, name: str, value: str) -> None:
        self.macros[_macro_name(name)] = value

    def table(self, name: str, body: str) -> None:
        (self.out_dir / f"{name}.tex").write_text(body + "\n", encoding="utf-8")

    def flush(self) -> None:
        lines = ["% AUTO-GENERATED by `python -m src.run_all` -- do not edit by hand."]
        lines += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in sorted(self.macros.items())]
        (self.out_dir / "macros.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


# --------------------------------------------------------------------------- paired tests
_METRIC_TEX = {"rmse_log": ("RMSE", "RMSE", False),
               "f1": ("F1", "FOne", True), "roc_auc": ("ROC-AUC", "AUC", True)}


def _paired_macro(task: str, pair: str, metric: str) -> str:
    """("A", "Our tree vs sklearn tree", "rmse_log") -> PairedAOurTreeVsSklearnTreeRMSE."""
    words = re.sub(r"[^A-Za-z ]", " ", pair).split()
    return "Paired" + task + "".join(w[0].upper() + w[1:] for w in words) + _METRIC_TEX[metric][1]


def _signed(x, d: int = 4) -> str:
    x = round(x, d) + 0.0                      # +0.0 turns -0.0 into 0.0
    return ("$+$" if x > 0 else "$-$" if x < 0 else "") + num(abs(x), d)


def _paired_verdict(r: dict) -> str:
    """Which model is really better, or that the test cannot tell them apart."""
    if not r["significant"]:
        return "no real difference"
    first, second = r["pair"].split(" vs ")
    higher = _METRIC_TEX[r["metric"]][2]
    return f"{first if (r['diff'] > 0) == higher else second} better"


def _write_paired(T: "TexWriter", R: dict) -> list[dict]:
    """Table + macros for the paired bootstrap comparisons (final models, then ensembles)."""
    rows = list(R["final"].get("paired", []))
    rows += R.get("bonus", {}).get("ensembles", {}).get("paired", [])
    body, last_task = [], None
    for r in rows:
        if last_task is not None and r["task"] != last_task:
            body.append(["MIDRULE"])
        last_task = r["task"]
        lo, hi = r["ci"]
        body.append([r["task"], tex_escape(r["pair"]), _METRIC_TEX[r["metric"]][0],
                     num(r["a"], 4), num(r["b"], 4),
                     f"{_signed(r['diff'])} [{_signed(lo)}, {_signed(hi)}]",
                     "$<$0.001" if r["p"] < 0.001 else num(r["p"], 3), tex_escape(_paired_verdict(r))])
    T.table("tab_paired", _tabular("@{}cllrrcrl@{}",
            ["Task", "Comparison (first vs second)", "Metric", "First", "Second",
             "Difference [95\\% CI]", "$p$", "Verdict"], body) if body else "(no paired comparisons)")

    # one Diff / CI / Word macro per (pair, metric), "--" when a model was not run
    have = {(r["task"], r["pair"], r["metric"]): r for r in rows}
    n_metrics = {"A": ("rmse_log",), "B": ("f1", "roc_auc")}
    for task, pair, _, _ in config.PAIRED_COMPARISONS + config.ENSEMBLE_PAIRS:
        for metric in n_metrics[task]:
            name = _paired_macro(task, pair, metric)
            r = have.get((task, pair, metric))
            T.macro(name + "Diff", _signed(r["diff"]) if r else "--")
            T.macro(name + "CI", f"[{_signed(r['ci'][0])}, {_signed(r['ci'][1])}]" if r else "--")
            T.macro(name + "Word", ("significant" if r["significant"] else "not significant") if r else "--")
    T.macro("NBoot", num(R["settings"].get("n_boot", config.N_BOOT)))
    T.macro("PairedN", str(len(rows)))
    T.macro("PairedNSig", str(sum(r["significant"] for r in rows)))
    ours_vs_sk = [r for r in rows if "sklearn" in r["pair"] or r["pair"] in
                  ("Pegasos vs LinearSVC", "RFF SVM vs SVC (RBF)")]
    T.macro("PairedNOursVsSk", str(len(ours_vs_sk)))
    T.macro("PairedNOursVsSkSig", str(sum(r["significant"] for r in ours_vs_sk)))
    return rows


# --------------------------------------------------------------------------- verdicts
def _verdicts(T: TexWriter, R: dict) -> None:
    """
    Outcome-dependent WORDS for the prose ("beats" vs "trails"), computed from
    the numbers so the text stays true when the data or settings change.
    """
    fin = R["final"]
    reg, clf = fin["regression"], fin["classification"]
    tree = reg["Ours: decision tree"]["metrics"]["rmse_log"]
    ridge = reg["Ours: ridge (bonus)"]["metrics"]["rmse_log"]
    sk_tree = reg["sklearn DecisionTreeRegressor"]["metrics"]["rmse_log"]
    T.macro("TreeVsRidgeWord", "beats" if tree < ridge else "trails")
    T.macro("TreeVsSkTreeDiff", num(abs(tree - sk_tree), 4))
    ours = {k: v["metrics"]["f1"] for k, v in clf.items() if k.startswith("Ours")}
    best_ours = max(ours, key=ours.get)
    T.macro("BestOurClf", tex_escape(best_ours.replace("Ours: ", "our ")))
    T.macro("BestOurClfFOne", num(ours[best_ours]))
    best_all = max(clf, key=lambda k: clf[k]["metrics"]["f1"])
    T.macro("BestAnyClf", tex_escape(best_all.replace("Ours: ", "our ")))
    T.macro("BestOverallClause", "which is also the best model overall" if best_all == best_ours else
            "while the best model overall is " + tex_escape(best_all.replace("Ours: ", "our ")) +
            f" (F1 {num(clf[best_all]['metrics']['f1'])})")
    lin = clf["Ours: linear SVM (Pegasos)"]["metrics"]["f1"]
    rff = clf["Ours: RBF SVM (RFF + Pegasos)"]["metrics"]["f1"]
    T.macro("RFFMinusLinear", ("+" if rff >= lin else "$-$") + num(abs(rff - lin)))
    T.macro("RFFVsLinearWord", "improves on" if rff > lin + 0.005 else
            ("matches" if abs(rff - lin) <= 0.005 else "falls short of"))
    tclf = clf["Ours: decision tree"]["metrics"]["f1"]
    T.macro("SVMVsTreeWord", "outperforms" if max(lin, rff) > tclf + 0.005 else
            ("matches" if abs(max(lin, rff) - tclf) <= 0.005 else "trails"))
    sk_lin = clf["sklearn LinearSVC"]["metrics"]["f1"]
    tm, sm = clf["Ours: decision tree"]["metrics"], clf["Ours: linear SVM (Pegasos)"]["metrics"]
    if tm["f1"] > sm["f1"] and tm["roc_auc"] < sm["roc_auc"] - 0.02:
        T.macro("AUCContrastSentence",
                f"By ROC-AUC the order flips ({num(tm['roc_auc'])} for the tree against {num(sm['roc_auc'])} for the "
                "SVM): the selected tree grows nearly pure leaves, so its probabilities are almost binary and rank "
                "listings poorly, while SVM margins grade them smoothly.")
    else:
        T.macro("AUCContrastSentence", "")
    T.macro("PegasosVsLiblinearFOneDiff", num(abs(lin - sk_lin), 3))
    cc = R["tree"]["criterion_comparison"]
    g, e = cc["gini"]["val_f1"], cc["entropy"]["val_f1"]
    T.macro("CritWinner", "Gini" if g >= e else "entropy")
    T.macro("CritDiff", num(abs(g - e), 3))
    T.macro("CritSimilarity", "behave almost identically" if abs(g - e) < 0.01 else "differ noticeably")
    lc = R["tree"]["learning_curve"]["reg_va"]
    still = len(lc) > 1 and lc[-1] < lc[-2] - 0.002
    T.macro("LCVerdict", "validation error is still falling at the full training size, so more data "
            "would still help" if still else "validation error has flattened out, so more data of the "
            "same kind would help little")
    conv = R["svm"]["convergence"]["batch_final_objective"]
    k1 = next((v for k, v in conv.items() if k.startswith("batch 1,")), None)
    kb = next((v for k, v in conv.items() if k.startswith("batch") and "last" in k and not k.startswith("batch 1,")), None)
    kf = conv.get("full batch")
    if k1 and kb:
        T.macro("BatchVerdict", "make as much progress per epoch as" if abs(kb - k1) / k1 < 0.05 else
                ("make more progress per epoch than" if kb < k1 else "make somewhat less progress per epoch than"))
    else:
        T.macro("BatchVerdict", "compare with")
    T.macro("FullBatchVerdict", "lags far behind" if (kf and kb and kf > 1.1 * kb) else "ends close to the mini-batch runs")
    rc = R["svm"]["rff_components"]
    D_, auc_, err_ = np.array(rc["D"], float), np.array(rc["val_auc"], float), np.array(rc["kernel_err"], float)
    slope = float(np.polyfit(np.log(D_), np.log(err_), 1)[0]) if len(D_) > 1 else float("nan")
    T.macro("RFFErrSlope", num(slope, 2).replace("-", "$-$"))
    quarter = auc_[D_ <= D_.max() / 4]
    sat = len(quarter) and (auc_.max() - quarter.max()) < 0.005
    T.macro("RFFDVerdict", "saturates well before the largest $D$" if sat else "keeps improving up to the largest $D$")
    grid = R["svm"]["rff_grid"]
    g_vals = sorted({r["gamma"] for r in grid})
    l_vals = sorted({r["lambda_"] for r in grid})
    br = R["svm"]["best_rff"]
    edges = []
    if br["gamma"] == g_vals[0]:
        edges.append("the smallest bandwidth $\\gamma$")
    elif br["gamma"] == g_vals[-1]:
        edges.append("the largest bandwidth $\\gamma$")
    if br["lambda_"] == l_vals[0]:
        edges.append("the weakest regularisation $\\lambda$")
    elif br["lambda_"] == l_vals[-1]:
        edges.append("the strongest regularisation $\\lambda$")
    if edges:
        note = ("Validation picks " + " and ".join(edges) + " in the grid"
                + (": the RBF kernel prefers to be nearly linear on these features, so the extension adds little over the linear SVM."
                   if br["gamma"] == g_vals[0] else ", so the optimum may lie just outside it."))
    else:
        note = "Both selected values lie inside the grid."
    T.macro("RFFGridNote", note)
    dr = R["analysis"]["decile_residuals"]["Our tree"]
    T.macro("TopDecileWord", "under-predicts" if dr[-1] < 0 else "over-predicts")
    T.macro("BottomDecileWord", "over-predicts" if dr[0] > 0 else "under-predicts")
    T.macro("ShrinkageSentence",
            "Leaves average many listings, which pulls the extremes towards the mean; this is the "
            "variance-reduction side of the bias--variance trade-off." if (dr[-1] < 0 < dr[0]) else
            "The errors at the extremes do not follow the usual shrink-to-the-mean pattern, which "
            "points to mislabelled or atypical listings in the tails.")
    groups = R["analysis"]["error_groups"].get("By listings in district (dev)", [])
    if len(groups) >= 2:
        T.macro("SparseDistrictSentence",
                f"The test MAE is {num(groups[0][1])} for listings whose district has "
                f"{tex_escape(groups[0][0])} training examples, against {num(groups[-1][1])} for "
                f"{tex_escape(groups[-1][0])}: rare districts fall into the ``other'' column and fall "
                "back on coordinates.")
    elif groups:
        T.macro("SparseDistrictSentence",
                f"Every test listing's district has {tex_escape(groups[0][0])} training examples, so "
                "district sparsity does not show up in this split.")
    else:
        T.macro("SparseDistrictSentence", "")
    a_ = R["analysis"]["tree_vs_sklearn"]["regression"]
    if a_["root_ours"] and a_["root_sk"] and a_["root_ours"][0] == a_["root_sk"][0] \
            and abs(a_["root_ours"][1] - a_["root_sk"][1]) < 1e-3:
        T.macro("RootSplitSentence", "Both trees choose the same root split ("
                + tex_escape(f"{a_['root_ours'][0]} <= {a_['root_ours'][1]:.3f}") + ").")
    elif a_["root_ours"] and a_["root_sk"] and a_.get("root_same_partition"):
        T.macro("RootSplitSentence", "At the root both trees send the same rows left: ours splits on "
                + tex_escape(f"{a_['root_ours'][0]} <= {a_['root_ours'][1]:.3f}") + ", scikit-learn on the equivalent "
                + tex_escape(f"{a_['root_sk'][0]} <= {a_['root_sk'][1]:.3f}") + " (an exact tie between monotone transforms of the same feature).")
    elif a_["root_ours"] and a_["root_sk"]:
        T.macro("RootSplitSentence", "The root splits are " + tex_escape(f"{a_['root_ours'][0]} <= {a_['root_ours'][1]:.3f}")
                + " (ours) and " + tex_escape(f"{a_['root_sk'][0]} <= {a_['root_sk'][1]:.3f}") + " (scikit-learn).")
    else:
        T.macro("RootSplitSentence", "")
    if "bonus" in R:
        ab = R["bonus"]["unsupervised"]["ablation"]
        T.macro("AblationWord", "lowers" if ab["val_rmse_with_clusters"] < ab["val_rmse_without"] - 1e-4
                else "does not lower")
        e_ = R["bonus"]["ensembles"]
        rf_ = e_["rf_reg"]["ours"]["rmse_log"]
        T.macro("ForestGainPct", pct(1 - rf_ / tree))
        T.macro("BoostGainPct", pct(1 - e_["gb_reg"]["ours"]["rmse_log"] / tree))
        T.macro("ForestVsTreeWord", "lowers" if rf_ < tree else "does not lower")
        T.macro("EnsembleVerdict", "which is why our forest beats the single tree" if rf_ < tree else
                "although on this split our forest does not beat the single tree")
        gbc = R["bonus"]["ensembles"]["curves"]["gb"]
        T.macro("BoostCurveVerdict", "falls steadily" if gbc[-1] <= min(gbc) + 1e-9 else "falls and then flattens")
    else:
        for k in ("AblationWord", "ForestGainPct", "BoostGainPct", "ForestVsTreeWord", "BoostCurveVerdict"):
            T.macro(k, "--")
        T.macro("EnsembleVerdict", "which is why ensembles usually beat a single tree")
    a = R["analysis"]["tree_vs_sklearn"]["regression"]["structure"]
    causes = ["exact gain ties"]
    if a["max_threshold_diff"] > 0 or a.get("float32_divergence", 0):
        causes.append("scikit-learn's float32 cast of the features")
    if a["gain_mismatch"]:
        causes.append(f"{a['gain_mismatch']} unexplained split(s)")
    T.macro("TreeGapCause", " and ".join(causes))


# --------------------------------------------------------------------------- tables
def scope_dropped_categories(counts: dict | None) -> str:
    """'torpaq 3,315, obyekt 2,526' for the categories outside config.KEEP_CATEGORIES."""
    kept = {normalize_name(c) for c in (config.KEEP_CATEGORIES or [])}
    return ", ".join(f"{k} {v:,}" for k, v in (counts or {}).items() if normalize_name(k) not in kept) or "none"


def _tabular(cols: str, header: list[str], rows: list[list[str]], size=r"\footnotesize") -> str:
    out = [size, f"\\begin{{tabular}}{{{cols}}}", r"\toprule", " & ".join(header) + r" \\", r"\midrule"]
    for r in rows:
        out.append(r"\midrule" if r == ["MIDRULE"] else " & ".join(r) + r" \\")
    out += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(out)


def _bold_best(values: list, higher: bool) -> list[bool]:
    arr = np.array([np.nan if v is None else v for v in values], float)
    if np.all(np.isnan(arr)):
        return [False] * len(values)
    best = np.nanmax(arr) if higher else np.nanmin(arr)
    return [bool(np.isfinite(a) and np.isclose(a, best)) for a in arr]


EXPLAIN_MACROS = ("ExplainRefModel", "PermTopReg", "PermTopClf", "PermTopRegGroup", "PermTopClfGroup",
                  "PermAgreeReg", "PermAgreeClf", "PermRepeats", "PermGroups",
                  "WeakDistrict", "WeakDistrictRMSE", "WeakDistrictN", "StrongDistrict", "StrongDistrictRMSE",
                  "OverallRefRMSE", "WeakBand", "WeakBandRMSE", "StrongBand", "StrongBandRMSE",
                  "TopBandBias", "BottomBandBias", "WeakTierDistrict", "WeakTierDistrictErr",
                  "WeakTierBand", "WeakTierBandErr")


def _agree_sentence(top1: dict) -> str:
    groups = set(top1.values())
    if len(groups) == 1:
        return f"All {len(top1)} models rank {tex_escape(next(iter(groups)))} first."
    parts = ", ".join(f"{tex_escape(m.replace('Our ', ''))}: {tex_escape(g)}" for m, g in top1.items())
    return f"The models disagree on the most important feature ({parts})."


def _explain(T: TexWriter, R: dict) -> None:
    """Permutation importance + error breakdown (src/explain.py)."""
    E = R.get("explain")
    if not E:
        for k in EXPLAIN_MACROS:
            T.macro(k, "--")
        T.table("tab_error_district", "(explanations skipped)")
        T.table("tab_error_band", "(explanations skipped)")
        return
    ref = E["ref_reg"]
    T.macro("ExplainRefModel", tex_escape(ref.replace("Our ", "our ")))
    T.macro("PermTopReg", tex_escape(", ".join(f"{g} (RMSE +{v:.3f})" for g, v in E["top_reg"][:4])))
    T.macro("PermTopClf", tex_escape(", ".join(f"{g} (AUC -{v:.3f})" for g, v in E["top_clf"][:4])))
    T.macro("PermTopRegGroup", tex_escape(E["top_reg"][0][0]))
    T.macro("PermTopClfGroup", tex_escape(E["top_clf"][0][0]))
    T.macro("PermAgreeReg", _agree_sentence(E["top1_reg"]))
    T.macro("PermAgreeClf", _agree_sentence(E["top1_clf"]))
    T.macro("PermRepeats", str(E["n_repeats"]))
    T.macro("PermGroups", str(E["n_groups"]))

    reg_models = list(E["overall_rmse"])
    clf_models = list(E["overall_tier_err"])
    short = {"Our tree": "Tree", "Our ridge": "Ridge", "Our random forest": "RF",
             "Our gradient boosting": "GB", "Our RFF SVM": "SVM"}

    def table(rows, first):
        header = [first, "$n$"] + [short.get(m, m) for m in reg_models] + \
                 [f"{short.get(m, m)} err." for m in clf_models]
        body = [[tex_escape(r["group"]), num(r["n"], 0)]
                + [num(r["rmse"][m]) for m in reg_models]
                + [pct(r["tier_err"][m]) for m in clf_models] for r in rows]
        body.append(["MIDRULE"])
        body.append(["All test", num(sum(r["n"] for r in rows), 0)]
                    + [num(E["overall_rmse"][m]) for m in reg_models]
                    + [pct(E["overall_tier_err"][m]) for m in clf_models])
        cols = "@{}lr" + "c" * len(reg_models) + "c" * len(clf_models) + "@{}"
        return _tabular(cols, header, body, size=r"\scriptsize")

    T.table("tab_error_district", table(E["by_district"], "District"))
    T.table("tab_error_band", table(E["by_price_band"], "Price (AZN)"))
    T.macro("OverallRefRMSE", num(E["overall_rmse"][ref]))

    named = [r for r in E["by_district"] if r["group"] not in ("other", "(none)")] or E["by_district"]
    weak = max(named, key=lambda r: r["rmse"][ref])
    strong = min(named, key=lambda r: r["rmse"][ref])
    T.macro("WeakDistrict", tex_escape(weak["group"]))
    T.macro("WeakDistrictRMSE", num(weak["rmse"][ref]))
    T.macro("WeakDistrictN", num(weak["n"], 0))
    T.macro("StrongDistrict", tex_escape(strong["group"]))
    T.macro("StrongDistrictRMSE", num(strong["rmse"][ref]))
    bands = E["by_price_band"]
    wb = max(bands, key=lambda r: r["rmse"][ref])
    sb = min(bands, key=lambda r: r["rmse"][ref])
    T.macro("WeakBand", tex_escape(wb["group"]))
    T.macro("WeakBandRMSE", num(wb["rmse"][ref]))
    T.macro("StrongBand", tex_escape(sb["group"]))
    T.macro("StrongBandRMSE", num(sb["rmse"][ref]))
    T.macro("BottomBandBias", f"${bands[0]['bias'][ref]:+.3f}$")
    T.macro("TopBandBias", f"${bands[-1]['bias'][ref]:+.3f}$")
    shrink = all(bands[0]["bias"][m] > 0 and bands[-1]["bias"][m] < 0 for m in reg_models)
    T.macro("ShrinkSentence",
            "Every model pulls the extremes towards the middle: cheap listings are over-priced "
            "and luxury ones under-priced." if shrink else
            "Not every model shows the same sign of bias at both ends of the price range.")
    rc = E.get("district_rank_corr_mean")
    if rc is None:
        T.macro("DistrictRankCorr", "")
    else:
        word = "largely shared" if rc >= 0.5 else "only partly shared" if rc >= 0.2 else "not shared"
        T.macro("DistrictRankCorr",
                f"Which districts are hard is {word} across models (mean pairwise Spearman "
                f"correlation of per-district RMSE {rc:.2f}), so "
                + ("the weak spots lie mainly in the data, not in one model." if rc >= 0.5 else
                   "part of the difficulty is model-specific."))
    clf_ref = clf_models[-1]
    wtd = max(named, key=lambda r: r["tier_err"][clf_ref])
    wtb = max(bands, key=lambda r: r["tier_err"][clf_ref])
    T.macro("WeakTierDistrict", tex_escape(wtd["group"]))
    T.macro("WeakTierDistrictErr", pct(wtd["tier_err"][clf_ref]))
    T.macro("WeakTierBand", tex_escape(wtb["group"]))
    T.macro("WeakTierBandErr", pct(wtb["tier_err"][clf_ref]))
    T.macro("ThresholdBandNote", ", the band that contains the tier threshold"
            if wtb["group"] == E.get("threshold_band") else "")


def write_all(R: dict, results_dir: Path, tex_dir: Path) -> None:
    results_dir = Path(results_dir)
    results_dir.mkdir(parents=True, exist_ok=True)
    (results_dir / "metrics.json").write_text(json.dumps(to_jsonable(R), indent=2, ensure_ascii=False),
                                              encoding="utf-8")
    T = TexWriter(tex_dir)
    data, eda, tree, svm, fin = R["data"], R["eda"], R["tree"], R["svm"], R["final"]
    cv = R.get("cv")

    # ---------------- data
    T.macro("NRaw", num(data["n_raw"]))
    T.macro("NClean", num(data["n_clean"]))
    T.macro("NTrain", num(data["n_train"]))
    T.macro("NVal", num(data["n_val"]))
    T.macro("NTest", num(data["n_test"]))
    T.macro("NDev", num(data["n_train"] + data["n_val"]))
    T.macro("NFeatures", num(data["n_features"]))
    T.macro("NNumericFeatures", num(data["n_numeric_features"]))
    T.macro("DataFile", tex_escape(data["file"]))
    T.macro("DataSHA", tex_escape(data["sha256"][:12]))
    T.macro("TierThreshold", num(data["tier_threshold_train"], 0))
    T.macro("TierThresholdDev", num(fin["threshold_dev"], 0))
    T.macro("PremiumTrain", pct(data["premium_share"]["train"]))
    T.macro("PremiumVal", pct(data["premium_share"]["val"]))
    T.macro("PremiumTest", pct(data["premium_share"]["test"]))
    T.macro("LeakageCols", tex_escape(", ".join(data["dropped_columns"].get("leakage", [])) or "none found"))
    T.macro("IdentifierCols", tex_escape(", ".join(data["dropped_columns"].get("identifiers", [])) or "none found"))
    T.macro("MetaCols", tex_escape(", ".join(data["dropped_columns"].get("listing_meta", [])) or "none found"))
    cur = data["currency_counts"]
    T.macro("NonAZNListings", num(int(sum(v for k, v in cur.items() if k != "AZN"))))
    steps_d = dict((name, n) for name, n in data["cleaning_steps"])
    T.macro("NUniqueListings", num(steps_d.get("repeat scrapes of a listing removed (latest kept)", data["n_raw"])))
    T.macro("NResidential", num(steps_d.get("residential categories only", data["n_raw"])))
    sp = data.get("scrape_period") or ["--", "--"]
    T.macro("ScrapeStart", tex_escape(sp[0]))
    T.macro("ScrapeEnd", tex_escape(sp[1]))
    T.macro("ScopeDroppedCats", tex_escape(scope_dropped_categories(data.get("category_counts_before_scope"))))
    T.macro("CurrencyBreakdown", tex_escape(", ".join(f"{k} {v:,}" for k, v in cur.items())))
    T.macro("CurrencySentence", "every price is already in AZN" if set(cur) <= {"AZN"} else
            "prices come in several currencies (" + tex_escape(", ".join(f"{k} {v:,}" for k, v in cur.items())) + ")")
    st = eda["stats"]
    T.macro("PriceMedian", num(st["price_median"], 0))
    T.macro("PriceMean", num(st["price_mean"], 0))
    T.macro("PricePOne", num(st["price_p01"], 0))
    T.macro("PricePNinetyNine", num(st["price_p99"], 0))
    T.macro("PriceSkew", num(st["price_skew"], 2))
    T.macro("LogPriceSkew", num(st["logprice_skew"], 2))
    T.macro("CorrAreaPrice", num(st["corr_logarea_logprice"], 2))
    T.macro("PpmMedian", num(st["ppm_median"], 0))

    steps = data["cleaning_steps"]
    rows = []
    prev = None
    for name, n in steps:
        removed = "" if prev is None else num(prev - n)
        rows.append([tex_escape(name), num(n), removed])
        prev = n
    T.table("tab_cleaning", _tabular("@{}lrr@{}", ["Step", "Rows left", "Removed"], rows))

    miss = data["missing_after_cleaning"]
    worst_missing = sorted(((k, v) for k, v in miss.items() if v > 0 and k != "description"),
                           key=lambda kv: -kv[1])[:5]
    T.macro("MissingSummary", tex_escape(", ".join(f"{k} {100 * v:.1f}%" for k, v in worst_missing)) or "none")
    rows = [
        ["Rows (raw / cleaned)", f"{num(data['n_raw'])} / {num(data['n_clean'])}"],
        ["Features after encoding", num(data["n_features"])],
        ["Train / Val / Test", f"{num(data['n_train'])} / {num(data['n_val'])} / {num(data['n_test'])}"],
        ["Tier threshold (train median)", f"{num(data['tier_threshold_train'], 0)} AZN"],
        ["Premium share train / val / test",
         f"{pct(data['premium_share']['train'])} / {pct(data['premium_share']['val'])} / {pct(data['premium_share']['test'])}"],
        ["Median price (train)", f"{num(st['price_median'], 0)} AZN"],
        ["Skewness price / log(price)", f"{num(st['price_skew'], 2)} / {num(st['logprice_skew'], 2)}"],
    ]
    T.table("tab_dataset", _tabular("@{}lr@{}", ["Property", "Value"], rows))

    # ---------------- tree studies
    bc, br = tree["best_clf"], tree["best_reg"]
    T.macro("TreeClfCrit", bc["criterion"])
    T.macro("TreeClfDepth", str(bc["max_depth"]))
    T.macro("TreeClfLeaf", str(bc["min_samples_leaf"]))
    T.macro("TreeClfValFOne", num(bc["val_f1"]))
    for crit, nm in (("gini", "Gini"), ("entropy", "Entropy")):
        c = tree["criterion_comparison"][crit]
        T.macro(f"{nm}ValFOne", num(c["val_f1"]))
        T.macro(f"{nm}ValAUC", num(c["val_auc"]))
        T.macro(f"{nm}Depth", str(c["max_depth"]))
        T.macro(f"{nm}Leaf", str(c["min_samples_leaf"]))
    T.macro("TreeRegDepth", str(br["max_depth"]))
    T.macro("TreeRegLeaf", str(br["min_samples_leaf"]))
    T.macro("TreeRegMinDec", "0" if br["min_impurity_decrease"] == 0 else sci(br["min_impurity_decrease"]))
    T.macro("TreeRegValRMSE", num(br["val_rmse"]))
    dc = tree["depth_curve_reg"]
    T.macro("TreeDeepTrainRMSE", num(dc["train"][-1]))
    T.macro("TreeDeepValRMSE", num(dc["val"][-1]))
    T.macro("TreeDeepDepth", str(dc["depths"][-1]))
    T.macro("TreeShallowValRMSE", num(dc["val"][0]))
    best_val_unpruned = int(np.argmin(dc["val"]))
    T.macro("TreeBestDepthUnpruned", str(dc["depths"][best_val_unpruned]))
    md = tree["min_decrease"]
    T.macro("MinDecNodesFirst", num(md["nodes"][0]))
    T.macro("MinDecNodesLast", num(md["nodes"][-1]))
    T.macro("MinDecLast", sci(md["grid"][-1]))
    lc = tree["learning_curve"]
    T.macro("LCGapSmall", num(lc["reg_va"][0] - lc["reg_tr"][0]))
    T.macro("LCGapFull", num(lc["reg_va"][-1] - lc["reg_tr"][-1]))

    # ---------------- svm studies
    b, rb = svm["best"], svm["best_rff"]
    T.macro("SVMLambda", sci(b["lambda_"]))
    T.macro("SVMC", f"{b['C']:.3g}")
    T.macro("SVMValFOne", num(b["val_f1"]))
    T.macro("SVMMarginVal", num(b["margin"]))
    T.macro("SVMSVFracVal", pct(b["sv_frac"]))
    T.macro("RFFGamma", num(rb["gamma"], 3))
    T.macro("RFFLambda", sci(rb["lambda_"]))
    T.macro("RFFD", num(R["settings"]["rff_components"]))
    T.macro("RFFValFOne", num(rb["val_f1"]))
    conv = svm["convergence"]
    T.macro("ObjFirst", num(conv["objective_first"]))
    T.macro("ObjLast", num(conv["objective_last"], 4))
    rc = conv.get("rel_change_last_5_epochs")
    T.macro("ObjRelChange", "--" if rc is None else pct(rc, 2))
    T.macro("SVMEpochs", str(R["settings"]["svm_epochs"]))
    T.macro("SVMBatch", str(R["settings"]["svm_batch"]))
    bt = conv["batch_timings_s"]
    T.macro("BatchTimes", tex_escape("; ".join(f"{k}: {v:.2f}s" for k, v in bt.items())))
    lam_rows = []
    for r in svm["sweep"]:
        mark = r is b or r["lambda_"] == b["lambda_"]
        cells = [sci(r["lambda_"]), f"{r['C']:.3g}", num(r["w_norm"], 2),
                 num(r["margin"], 3), pct(r["sv_frac"]), num(r["train_f1"]), num(r["val_f1"]), num(r["val_auc"])]
        lam_rows.append([f"\\textbf{{{c}}}" if mark else c for c in cells])
    T.table("tab_svm_sweep", _tabular("@{}lrrrrrrr@{}",
            ["$\\lambda$", "$C$", "$\\|\\mathbf{w}\\|$", "$2/\\|\\mathbf{w}\\|$", "SV", "Tr F1", "Val F1", "Val AUC"],
            lam_rows))

    # ---------------- final results tables
    def reg_rows():
        names = list(fin["regression"].keys())
        test_rmse = [fin["regression"][n]["metrics"]["rmse_log"] for n in names]
        bold = _bold_best(test_rmse, higher=False)
        rows = []
        for n, bb in zip(names, bold):
            m = fin["regression"][n]["metrics"]
            c = cv["regression"].get(n) if cv else None
            ci = m.get("rmse_log_ci")
            rmse_s = num(m["rmse_log"])
            rmse_s = f"\\textbf{{{rmse_s}}}" if bb else rmse_s
            rows.append([tex_escape(n), pm(c["rmse_log"]) if c else "--", pm(c["r2_log"]) if c else "--",
                         rmse_s + (f" [{num(ci[0])}, {num(ci[1])}]" if ci else ""),
                         num(m["r2_log"]), num(m["mae_azn"], 0), pct(m["mape"]),
                         num(fin["regression"][n]["times"]["fit_s"], 2)])
        return rows

    T.table("tab_results_reg", _tabular("@{}lccccrrr@{}",
            ["Model", "CV RMSE (log)", "CV $R^2$ (log)", "Test RMSE (log) [95\\% CI]", "Test $R^2$",
             "Test MAE (AZN)", "MAPE", "Fit (s)"], reg_rows()))

    def clf_rows():
        names = list(fin["classification"].keys())
        f1s = [fin["classification"][n]["metrics"]["f1"] for n in names]
        bold = _bold_best(f1s, higher=True)
        rows = []
        for n, bb in zip(names, bold):
            m = fin["classification"][n]["metrics"]
            c = cv["classification"].get(n) if cv else None
            f1 = num(m["f1"])
            f1 = f"\\textbf{{{f1}}}" if bb else f1
            rows.append([tex_escape(n) + ("$^\\dagger$" if n in fin.get("notes", {}) else ""),
                         pm(c["f1"]) if c else "--", pm(c["roc_auc"]) if c else "--",
                         num(m["accuracy"]), num(m["precision"]), num(m["recall"]),
                         f1 + f" [{num(m['f1_ci'][0])}, {num(m['f1_ci'][1])}]",
                         num(m["roc_auc"]) + (f" [{num(m['auc_ci'][0])}, {num(m['auc_ci'][1])}]"
                                               if m.get("auc_ci") else ""), num(m["pr_auc"]),
                         num(fin["classification"][n]["times"]["fit_s"], 2)])
        return rows

    T.table("tab_results_clf", _tabular("@{}lccccccccr@{}",
            ["Model", "CV F1", "CV ROC-AUC", "Acc", "Prec", "Rec", "Test F1 [95\\% CI]", "AUC [95\\% CI]", "PR-AUC", "Fit (s)"],
            clf_rows()))
    T.macro("SVCNote", tex_escape(next(iter(fin.get("notes", {}).values()), "")))

    # compact headline table (both tasks in one place)
    head = [("Ours: decision tree", "Ours: decision tree"),
            ("Ours: linear SVM (Pegasos)", None), ("Ours: RBF SVM (RFF + Pegasos)", None),
            ("Ours: ridge (bonus)", None),
            ("sklearn DecisionTree*", "sklearn"), ("sklearn LinearSVC", None), ("sklearn SVC (RBF)", None)]
    rows = []
    for name, _ in head:
        reg_key = {"sklearn DecisionTree*": "sklearn DecisionTreeRegressor"}.get(name, name)
        clf_key = {"sklearn DecisionTree*": "sklearn DecisionTreeClassifier"}.get(name, name)
        a = cv["regression"].get(reg_key, {}).get("rmse_log") if cv else None
        bcv = cv["classification"].get(clf_key, {}).get("f1") if cv else None
        at = fin["regression"].get(reg_key, {}).get("metrics", {}).get("rmse_log")
        btt = fin["classification"].get(clf_key, {}).get("metrics", {}).get("f1")
        rows.append([tex_escape(name.replace("Ours: ", "Ours: ")),
                     pm(a) if a else "n/a", num(at) if at is not None else "n/a",
                     pm(bcv) if bcv else "n/a", num(btt) if btt is not None else "n/a"])
    T.table("tab_headline", _tabular("@{}lcccc@{}",
            ["Model", "A: RMSE (CV)", "A: test", "B: F1 (CV)", "B: test"], rows))

    # headline macros
    r_t = fin["regression"]["Ours: decision tree"]["metrics"]
    r_s = fin["regression"]["sklearn DecisionTreeRegressor"]["metrics"]
    r_c = fin["regression"]["Constant baseline (train median)"]["metrics"]
    r_r = fin["regression"]["Ours: ridge (bonus)"]["metrics"]
    T.macro("OurTreeRMSE", num(r_t["rmse_log"]))
    T.macro("OurTreeRtwo", num(r_t["r2_log"]))
    T.macro("OurTreeRtwoAZN", num(r_t["r2_azn"]))
    T.macro("OurTreeMAEAZN", num(r_t["mae_azn"], 0))
    T.macro("OurTreeMAPE", pct(r_t["mape"]))
    T.macro("SkTreeRMSE", num(r_s["rmse_log"]))
    T.macro("ConstRMSE", num(r_c["rmse_log"]))
    T.macro("RidgeRMSE", num(r_r["rmse_log"]))
    T.macro("RidgeAlpha", num(R["ridge"]["alpha"], 3 if R["ridge"]["alpha"] < 1 else 0))
    cm = fin["classification"]
    for key, nm in (("Ours: decision tree", "OurTreeClf"), ("Ours: linear SVM (Pegasos)", "OurSVM"),
                    ("Ours: RBF SVM (RFF + Pegasos)", "OurRFF"), ("sklearn DecisionTreeClassifier", "SkTreeClf"),
                    ("sklearn LinearSVC", "SkLinSVC"), ("sklearn SGDClassifier (hinge)", "SkSGD"),
                    ("sklearn SVC (RBF)", "SkSVC")):
        m = cm[key]["metrics"]
        T.macro(f"{nm}FOne", num(m["f1"]))
        T.macro(f"{nm}AUC", num(m["roc_auc"]))
        T.macro(f"{nm}Acc", num(m["accuracy"]))
        T.macro(f"{nm}Fit", num(cm[key]["times"]["fit_s"], 2))
    T.macro("OurTreeRegFit", num(fin["regression"]["Ours: decision tree"]["times"]["fit_s"], 2))
    T.macro("SkTreeRegFit", num(fin["regression"]["sklearn DecisionTreeRegressor"]["times"]["fit_s"], 3))
    if cv:
        T.macro("CVFolds", str(cv["folds"]))
        T.macro("CVOurTreeRMSE", pm(cv["regression"]["Ours: decision tree"]["rmse_log"]))
        T.macro("CVSkTreeRMSE", pm(cv["regression"]["sklearn DecisionTreeRegressor"]["rmse_log"]))
        T.macro("CVOurSVMFOne", pm(cv["classification"]["Ours: linear SVM (Pegasos)"]["f1"]))
        T.macro("CVOurTreeFOne", pm(cv["classification"]["Ours: decision tree"]["f1"]))
        T.macro("CVOurRFFFOne", pm(cv["classification"]["Ours: RBF SVM (RFF + Pegasos)"]["f1"]))
    else:
        for k in ("CVFolds", "CVOurTreeRMSE", "CVSkTreeRMSE", "CVOurSVMFOne", "CVOurTreeFOne", "CVOurRFFFOne"):
            T.macro(k, "--")

    # ---------------- analysis
    A = R["analysis"]
    rows = []
    for task, label in (("regression", "A (MSE)"), ("classification", "B (" + bc["criterion"] + ")")):
        c = A["tree_vs_sklearn"][task]
        st_ = c["structure"]
        rows.append([label, f"{c['ours_depth']} / {c['sk_depth']}", f"{num(c['ours_leaves'])} / {num(c['sk_leaves'])}",
                     num(st_["same_split"]), num(st_["same_partition"] + st_["tie_divergence"]),
                     num(st_.get("float32_divergence", 0)), num(st_["gain_mismatch"]), pct(c["test_agreement"])])
    T.table("tab_tree_compare", _tabular("@{}lccccccc@{}",
            ["Task", "Depth", "Leaves", "Same", "Ties", "f32", "Other", "Agree"], rows, size=r"\footnotesize"))
    reg_c, clf_c = A["tree_vs_sklearn"]["regression"], A["tree_vs_sklearn"]["classification"]
    T.macro("RegAgreement", pct(reg_c["test_agreement"]))
    T.macro("ClfAgreement", pct(clf_c["test_agreement"]))
    T.macro("RegSameSplit", num(reg_c["structure"]["same_split"]))
    T.macro("RegTies", num(reg_c["structure"]["tie_divergence"] + reg_c["structure"]["same_partition"]))
    T.macro("RegGainMismatch", num(reg_c["structure"]["gain_mismatch"]))
    T.macro("ClfGainMismatch", num(clf_c["structure"]["gain_mismatch"]))
    T.macro("ClfTies", num(clf_c["structure"]["tie_divergence"] + clf_c["structure"]["same_partition"]))
    T.macro("RegFloatDiv", num(reg_c["structure"].get("float32_divergence", 0)))
    T.macro("ClfFloatDiv", num(clf_c["structure"].get("float32_divergence", 0)))
    T.macro("FloatCollapsed", num(reg_c["float32_collapsed_values"]))
    T.macro("RootSplitOurs", tex_escape(f"{reg_c['root_ours'][0]} <= {reg_c['root_ours'][1]:.3f}") if reg_c["root_ours"] else "--")
    T.macro("RootSplitSk", tex_escape(f"{reg_c['root_sk'][0]} <= {reg_c['root_sk'][1]:.3f}") if reg_c["root_sk"] else "--")
    sm = A["svm_margin"]
    T.macro("SVMWNorm", num(sm["w_norm"]))
    T.macro("SVMMargin", num(sm["margin"]))
    T.macro("SVMNSV", num(sm["n_sv"]))
    T.macro("SVMSVFrac", pct(sm["sv_frac"]))
    lib = A["svm_vs_liblinear_objective"]
    T.macro("ObjPegasos", num(lib["pegasos"], 4))
    T.macro("ObjLiblinear", num(lib["liblinear"], 4))
    T.macro("ObjGap", pct((lib["pegasos"] - lib["liblinear"]) / lib["liblinear"], 2))
    T.macro("SVMLibAgree", pct(lib["prediction_agreement_test"]))
    imp = A["importance_reg"]
    T.macro("TopFeatReg", tex_escape(", ".join(f"{n} ({v:.2f})" for n, v in imp[:4])))
    T.macro("TopFeatClf", tex_escape(", ".join(f"{n} ({v:.2f})" for n, v in A["importance_clf"][:4])))
    T.macro("TopFeatOne", tex_escape(imp[0][0]))
    T.macro("TopFeatOneShare", pct(imp[0][1], 0))
    T.macro("SVMPosWeights", tex_escape(", ".join(n for n, _ in A["svm_weights_top_pos"][:4])))
    T.macro("SVMNegWeights", tex_escape(", ".join(n for n, _ in A["svm_weights_top_neg"][:4])))
    te = A["tier_errors"]
    T.macro("NearThresholdErrShare", pct(te["share_of_tree_errors_within_10pct"], 0))
    T.macro("NearThresholdSVMErrShare", pct(te["share_of_svm_errors_within_10pct"], 0))
    T.macro("NearThresholdRowShare", pct(te["share_of_rows_within_10pct"], 0))
    T.macro("FarThresholdErr", pct(te["tree_error_rate"][-1]))
    T.macro("NearestThresholdErr", pct(te["tree_error_rate"][0]))
    dr = A["decile_residuals"]["Our tree"]
    T.macro("BottomDecileBias", num(dr[0], 3))
    T.macro("TopDecileBias", num(dr[-1], 3))
    T.macro("ShareBigErrors", pct(A["share_abs_err_gt_50pct"]))
    eg = A["error_groups"]
    dist = eg.get("By listings in district (dev)", [])
    if dist:
        T.macro("SparseDistrictMAE", num(dist[0][1]))
        T.macro("SparseDistrictLabel", tex_escape(dist[0][0]))
        T.macro("DenseDistrictMAE", num(dist[-1][1]))
        T.macro("DenseDistrictLabel", tex_escape(dist[-1][0]))
    cat = eg.get("By category", [])
    if cat:
        worst = max(cat, key=lambda r: r[1])
        best = min(cat, key=lambda r: r[1])
        T.macro("WorstCategory", tex_escape(worst[0]))
        T.macro("WorstCategoryMAE", num(worst[1]))
        T.macro("BestCategory", tex_escape(best[0]))
        T.macro("BestCategoryMAE", num(best[1]))
    rows = [[num(w["true_azn"], 0), num(w["pred_azn"], 0), num(w["area_m2"], 0),
             "--" if w["rooms"] is None or np.isnan(w["rooms"]) else num(w["rooms"], 0),
             tex_escape(w["category"])[:22],
             tex_escape(w["location"])[:22]] for w in A["worst_predictions"][:6]]
    T.table("tab_worst", _tabular("@{}rrrrll@{}", ["True (AZN)", "Pred. (AZN)", "m$^2$", "Rooms", "Category", "Location"],
                                  rows, size=r"\scriptsize"))

    # ---------------- bonus
    if "bonus" in R:
        B = R["bonus"]
        e = B["ensembles"]
        rows = [
            ["Ours: single decision tree", num(r_t["rmse_log"]), num(r_t["r2_log"]), "--"],
            ["Ours: ridge (normal equations)", num(r_r["rmse_log"]), num(r_r["r2_log"]), "--"],
            ["Ours: random forest", num(e["rf_reg"]["ours"]["rmse_log"]), num(e["rf_reg"]["ours"]["r2_log"]),
             num(e["times"]["rf_reg_fit_s"], 1)],
            ["sklearn RandomForest", num(e["rf_reg"]["sklearn"]["rmse_log"]), num(e["rf_reg"]["sklearn"]["r2_log"]),
             num(e["times"]["sk_rf_reg_fit_s"], 1)],
            ["Ours: gradient boosting", num(e["gb_reg"]["ours"]["rmse_log"]), num(e["gb_reg"]["ours"]["r2_log"]),
             num(e["times"]["gb_fit_s"], 1)],
            ["sklearn GradientBoosting", num(e["gb_reg"]["sklearn"]["rmse_log"]), num(e["gb_reg"]["sklearn"]["r2_log"]),
             num(e["times"]["sk_gb_fit_s"], 1)],
        ]
        T.table("tab_bonus", _tabular("@{}lccr@{}", ["Task A model (test)", "RMSE (log)", "$R^2$", "Fit (s)"], rows))
        T.macro("RFRMSE", num(e["rf_reg"]["ours"]["rmse_log"]))
        T.macro("SkRFRMSE", num(e["rf_reg"]["sklearn"]["rmse_log"]))
        T.macro("GBRMSE", num(e["gb_reg"]["ours"]["rmse_log"]))
        T.macro("SkGBRMSE", num(e["gb_reg"]["sklearn"]["rmse_log"]))
        T.macro("RFClfFOne", num(e["rf_clf"]["ours"]["f1"]))
        T.macro("SkRFClfFOne", num(e["rf_clf"]["sklearn"]["f1"]))
        T.macro("RFTrees", str(R["settings"]["forest_trees"]))
        T.macro("GBTrees", str(R["settings"]["boost_trees"]))
        u = B["unsupervised"]
        T.macro("KMeansK", str(R["settings"]["kmeans_k"]))
        T.macro("AblationWithout", num(u["ablation"]["val_rmse_without"]))
        T.macro("AblationWith", num(u["ablation"]["val_rmse_with_clusters"]))
        T.macro("PCANinety", str(u["pca_components_for_90pct"]))
        T.macro("PCATwoShare", pct(u["pca_pc1_pc2_share"]))
        cl = sorted(u["clusters"], key=lambda r: -r["mae_log"])
        if cl:
            T.macro("WorstClusterMAE", num(cl[0]["mae_log"]))
            T.macro("WorstClusterID", str(cl[0]["cluster"]))
            T.macro("BestClusterMAE", num(cl[-1]["mae_log"]))
    else:
        for k in ("RFRMSE", "SkRFRMSE", "GBRMSE", "SkGBRMSE", "RFClfFOne", "SkRFClfFOne", "RFTrees",
                  "GBTrees", "KMeansK", "AblationWithout", "AblationWith", "PCANinety", "PCATwoShare",
                  "WorstClusterMAE", "WorstClusterID", "BestClusterMAE"):
            T.macro(k, "--")
        T.table("tab_bonus", "(bonus experiments skipped)")
    paired = _write_paired(T, R)
    _explain(T, R)
    _verdicts(T, R)
    T.macro("RunMode", "fast smoke-test" if R["settings"]["fast"] else "full")
    T.flush()

    # CSV copies of the main tables
    pd.DataFrame([{"model": n, **{k: v for k, v in d["metrics"].items() if not isinstance(v, (list, tuple))},
                   **d["times"]} for n, d in fin["regression"].items()]).to_csv(results_dir / "test_regression.csv", index=False)
    pd.DataFrame([{"model": n, **{k: v for k, v in d["metrics"].items() if not isinstance(v, (list, tuple))},
                   **d["times"]} for n, d in fin["classification"].items()]).to_csv(results_dir / "test_classification.csv", index=False)
    pd.DataFrame(svm["sweep"]).to_csv(results_dir / "svm_lambda_sweep.csv", index=False)
    if paired:
        pd.DataFrame([{**r, "ci_lo": r["ci"][0], "ci_hi": r["ci"][1]} for r in paired]).drop(columns="ci") \
            .to_csv(results_dir / "paired_tests.csv", index=False)
    if cv:
        rows = []
        for task in ("regression", "classification"):
            for n, d in cv[task].items():
                rows.append({"task": task, "model": n, **{f"{k}_mean": v[0] for k, v in d.items()},
                             **{f"{k}_std": v[1] for k, v in d.items()}})
        pd.DataFrame(rows).to_csv(results_dir / "cv_results.csv", index=False)


if __name__ == "__main__":
    # Rebuild the LaTeX macros/tables from a saved metrics.json without re-running experiments:
    #   python -m src.reporting [results/metrics.json] [report/generated]
    import sys

    src = Path(sys.argv[1]) if len(sys.argv) > 1 else config.RESULTS_DIR / "metrics.json"
    dst = Path(sys.argv[2]) if len(sys.argv) > 2 else config.GENERATED_TEX_DIR
    write_all(json.loads(src.read_text(encoding="utf-8")), src.parent, dst)
    print(f"rebuilt LaTeX tables/macros in {dst} from {src}")
